# http://travis-ci.org/#!/astraw/stdeb
language: python
python:
    - 2.7
install:
    - python setup.py --command-packages=stdeb.command bdist_deb
    - sudo dpkg -i deb_dist/*.deb
script:
    - ./test.sh
    - ./test-pypi-install.sh
branches:
  except:
    - pristine-tar
    - old-stable
    - zooko
