# http://travis-ci.org/#!/astraw/stdeb
language: python
python:
    - 2.7
before_install:
    - sudo apt-get update
    - sudo apt-get install python-all-dev debhelper python-setuptools apt-file
    - which python
    - dpkg --status python2.7

    # Fail early if not using a debian version of the distutils
    # install command. Otherwise the debhelper tools give a problem
    # with the --install-layout option not being understood.
    - grep -q install-layout /usr/lib/python2.7/distutils/command/install.py
install:
    - python setup.py --command-packages=stdeb.command bdist_deb
    - sudo dpkg -i deb_dist/*.deb
script:
    - ./test.sh
    - ./test-pypi-install.sh
branches:
  except:
    - pristine-tar
    - old-stable
    - zooko
