# http://travis-ci.org/#!/astraw/stdeb
language: python
python:
    - "2.7"
    - "3.3"
before_install:
    - sudo apt-get update
    - sudo apt-get install python-all-dev debhelper python-setuptools apt-file libxml2-dev python-requests
    - export PATH=/usr/bin:$PATH
install:
    # Build a .deb file and then install it.
    - python setup.py --command-packages=stdeb.command bdist_deb
    - sudo dpkg -i deb_dist/*.deb
script:
    - sudo ./test.sh
    - sudo ./test-pypi-install.sh
